# Args: <cam_file> <obj_file> <output_dir>
{
  "version": 3,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "pip": [
      "h5py"
    ]
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config":{
        "global": {
          "output_dir": "examples/front_3d",
          "max_bounces": 200,
          "diffuse_bounces": 200,
          "glossy_bounces": 200,
          "transmission_bounces": 200,
          "transparency_bounces": 200
        }
      }
    },
    {
      "module": "loader.Front3DLoader",
      "config": {
        "path": "<args:0>"
      }
    },
    {
      "module": "loader.CCMaterialLoader",
      "config": {
        "used_assets": ["Bricks", "Wood", "Carpet", "Tile", "Marble"]
      }
    },
    {
      "module": "materials.MaterialRandomizer",
      "config": {
        "randomization_level": 0.95,
        "manipulated_objects": {
          "provider": "getter.Entity",
          "conditions": {
            "name": "Floor.*"
          }
        },
        "materials_to_replace_with": {
          "provider": "getter.Material",
          "conditions": {
            "cp_is_cc_texture": True  # this will return all loaded cc textures
          }
        }
      }
    },
    {
      "module": "materials.MaterialRandomizer",
      "config": {
        "randomization_level": 1.0,
        "mode": "once_for_all",
        "manipulated_objects": {
          "provider": "getter.Entity",
          "conditions": {
            "name": "Baseboard.*"
          }
        },
        "materials_to_replace_with": {
          "provider": "getter.Material",
          "conditions": {
            "cp_is_cc_texture": True,  # this will return all loaded cc textures
            "cp_asset_name": "WoodFloor.*"
          }
        }
      }
    },
    {
      "module": "materials.MaterialRandomizer",
      "config": {
        "randomization_level": 1.0,
        "mode": "once_for_all",
        "manipulated_objects": {
          "provider": "getter.Entity",
          "conditions": {
            "name": "Door.*"
          }
        },
        "materials_to_replace_with": {
          "provider": "getter.Material",
          "conditions": {
            "cp_is_cc_texture": True,  # this will return all loaded cc textures
            "cp_asset_name": "WoodFloor.*"
          }
        }
      }
    },
    {
      "module": "materials.MaterialRandomizer",
      "config": {
        "randomization_level": 0.1,
        "manipulated_objects": {
          "provider": "getter.Entity",
          "conditions": {
            "name": "Wall.*"
          }
        },
        "materials_to_replace_with": {
          "provider": "getter.Material",
          "conditions": {
            "cp_is_cc_texture": True,  # this will return all loaded cc textures
            "cp_asset_name": "Marble.*"
          }
        }
      }
    },
    {
      "module": "lighting.LightLoader",
      "config": {
        "lights": [
          {
            "type": "POINT",
            "location": [5, -5, 5],
            "energy": 1000
          }
        ]
      }
    },
    {
      "module": "camera.CameraSampler",
      "config": {
        "cam_poses": [
          {
            "number_of_samples": 1,
            "location": {
              "provider":"sampler.Uniform3d",
              "max":[3.401, 1.6301, 1.3701],
              "min":[3.4, 1.63, 1.37]
            },
            "rotation": {
              "value": {
                "provider":"sampler.Uniform3d",
                "max":[1.338668, 0, 1.98],
                "min":[1.338, 0, 1.97]
              }
            }
          }
        ]
      }
    },
    {
      "module": "renderer.RgbRenderer",
      "config": {
        "output_key": "colors",
        "samples": 350,
        "render_normals": True,
        "render_depth": True,
      }
    },
    {
      "module": "writer.Hdf5Writer",
      "config": {
        "postprocessing_modules": {
          "depth": [
            {
              "module": "postprocessing.TrimRedundantChannels",
            }
          ]
        }
      }
    }
  ]
}
