# Args: <cam_file> <obj_file> <output_dir>
{
  "version": 2,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "pip": [
      "h5py"
    ]
  },
  "global": {
    "all": {
      "output_dir": "<args:2>"
    },
    "renderer": {
      "pixel_aspect_x": 1.333333333
    }
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config": {}
    },
    {
      "module": "loader.SuncgLoader",
      "config": {
        "path": "<args:1>"
      }
    },
    {
      "module": "camera.CameraLoader",
      "config": {
        "path": "<args:0>",
        "file_format": "location rotation/value _ _ _ fov _ _",
        "source_frame": ["X", "-Z", "Y"],
        "default_cam_param": {
          "rotation": {
            "format": "forward_vec"
          },
          "fov_is_half": true
        }
      }
    },
    {
      "module": "lighting.SuncgLighting",
    },
    {
      "module": "renderer.SegMapRenderer",
      "config": {
        "use_alpha": True
      }
    },
    {
      "module": "renderer.RgbRenderer",
      "config": {
        "use_alpha": True,
        "render_depth": true,
        "render_normals": True
      }
    },
    {
      "module": "writer.Hdf5Writer",
    }
  ]
}
