name: BlenderProcHelper

on: [push, workflow_dispatch]
  
jobs:
  build-linux:
    runs-on: [self-hosted]
    strategy:
      max-parallel: 1
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Pip install
      run: pip install pyyaml matplotlib numpy 
    - name: Run BlenderProcHelper
      run: python /home/$USER/workspace/BlenderProcHelper/github_action.py
