# Args: <cam_file> <obj_file> <dataset_name> <output_dir>
{
  "version": 3,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "pip": [
      "h5py",
      "pypng==0.0.20",
    ]
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config":{
        "global": {
          "output_dir": "<args:3>"
        }
      }
    },
    {
      "module": "loader.ObjectLoader",
      "config": {
        "path": "<args:1>", 
        "add_properties": {
            "cp_bop_dataset_name": "hb",
            "cp_category_id": "1"
        }, 
      },
    },
    {
      "module": "manipulators.EntityManipulator",
      "config": {
        "selector": {
          "provider": "getter.Entity",
          "conditions": {
            "type": "MESH"  # this guarantees that the object is a mesh, and not for example a camera
          }
        },  
        "matrix_world":
            [[0.331458, -0.6064861, 0.7227108, 0],
            [-0.9415833, -0.2610635, 0.2127592, 0],
            [ 0.05963787, -0.7510136, -0.6575879, 0],
            [ -44.74526765165741, 89.70402424862098, 682.3395750305427, 1.0]],
      },
    },
    {
      "module": "lighting.LightLoader",
      "config": {
        "lights": [
          {
            "type": "POINT",
            "location": [5, -5, 5],
            "energy": 1000
          }
        ]
      }
    },
    {
      "module": "camera.CameraLoader",
      "config": {
        "path": "<args:0>",
        "file_format": "cam2world_matrix",
        "source_frame": ["X", "-Y", "-Z"],
        "default_cam_param": {
          "cam_K": [537.4799, 0.0, 318.8965, 0.0, 536.1447, 238.3781, 0.0, 0.0, 1.0],
          "resolution_x": 640,
          "resolution_y": 480
        }
      }
    },
    {
      "module": "renderer.RgbRenderer",
      "config": {
        "samples": 350,
        "render_distance": True,
        "render_normals": True,
      }
    },
    {
      "module": "writer.BopWriter",
      "config": {
        "dataset": "<args:2>",
        "postprocessing_modules": {
          "distance": [
            {"module": "postprocessing.Dist2Depth"}
          ]
        }
      }
    },
    {
      "module": "writer.Hdf5Writer",
      "config": {
        "postprocessing_modules": {
          "distance": [
            {
              "module": "postprocessing.TrimRedundantChannels",
            }
          ]
        }
      }
    }
  ]
}
