# Args: <cam_file> <obj_file> <output_dir>
{
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "blender_version": "blender-2.80-linux-glibc217-x86_64",
    "bop_toolkit_path": "/home_local/<env:USER>/src/bop_toolkit/",
    "pip": [
      "h5py",
      "imageio",
      "pypng==0.0.18",
      "scipy==1.2.2"
    ]
  },
  "global": {
    "all": {
      "output_dir": "<args:1>"
    }
  },
  "modules": [
    {
      "name": "main.Initializer",
      "config": {}
    },
    {
      "name": "loader.BopLoader",
      "config": {
        "bop_dataset_path": "<args:0>",
        "split": "test",
        "scene_id": 3
      }
    },
    {
      "name": "lighting.LightLoader",
      "config": {
        "lights": [
          {
            "type": "AREA",
            "location": [0, 0, 5],
            "energy": 10000,
            "shape": "SQUARE",
            "size": 30
          }
        ]
      }
    },
    {
      "name": "renderer.NormalRenderer",
      "config": {
      }
    },
    {
      "name": "renderer.RgbRenderer",
      "config": {
        "samples": 200
      }
    },
    {
      "name": "writer.Hdf5Writer",
      "config": {
      }
    }
  ]
}
