# Args: <cam_file> <obj_file> <output_dir>
{
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "blender_version": "blender-2.80-linux-glibc217-x86_64",
    "pip": [
      "h5py",
      "imageio",
      "pypng==0.0.18",
      "scipy==1.2.2"
    ]
  },
  "global": {
    "all": {
      "output_dir": "<args:1>"
    },
    "sys_paths": ["/path/to/bop_toolkit"]
  },
  "modules": [
    {
      "name": "main.Initializer",
      "config": {}
    },
    {
      "name": "loader.BopLoader",
      "config": {
        "bop_dataset_path": "<args:0>",
        "mm2m": True,
        "split": "val",
        "scene_id": 3,
        "model_type": ""
      }
    },
    {
      "name": "lighting.LightSampler",
      "config": {
        "lights": [
          {
            "location": {
              "name": "ShellSampler",
              "parameters": {
                "center": [0, 0, -0.8],
                "radius_min": 1,
                "radius_max": 4,
                "elevation_min": 40,
                "elevation_max": 89
              }
            },
            "type": "POINT",
            "energy": 1000
          }
        ]
      }
    },
    {
      "name": "renderer.RgbRenderer",
      "config": {
        "samples": 150
      }
    },
    {
      "name": "renderer.SegMapRenderer",
      "config": {
        "map_by": "instance"
      }
    },
    {
      "name": "writer.Hdf5Writer",
      "config": {
      }
    }
  ]
}
