# Args: <cam_file> <obj_file> <output_dir>
{
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/src/foreign_packages/",
    "bop_toolkit_path": "/home_local/sund_ma/src/foreign_packages/bop/bop_toolkit-1/",
    "blender_version": "blender-2.80-linux-glibc217-x86_64",
    "pip": [
      "h5py",
      "imageio",
      "png"
    ]
  },
  "global": {
    "all": {
      "output_dir": "<args:1>"
    }
  },
  "modules": [
    {
      "name": "main.Initializer",
      "config": {}
    },
    {
      "name": "loader.BopLoader",
      "config": {
        "datasets_path": "<args:0>",
        "scene_id": 1
      }
    },
    {
      "name": "lighting.LightLoader",
      "config": {
        "lights": [
          {
            "type": "AREA",
            "location": [0, 0, 5],
            "energy": 10000,
            "shape": "SQUARE",
            "size": 30
          }
        ]
      }
    },
    # {
    #   "name": "camera.CameraLoader",
    #   "config": {
    #     "path": "<args:0>",
    #     "file_format": "location rotation",
    #     "default_cam_param": {
    #       "fov": 1
    #     }
    #   }
    # },
    {
      "name": "renderer.NormalRenderer",
      "config": {
      }
    },
    {
      "name": "renderer.RgbRenderer",
      "config": {
        "samples": 350
      }
    },
    {
      "name": "writer.Hdf5Writer",
      "config": {
      }
    }
  ]
}
