{
  "global": {
    "all": {
      "output_dir": "debug"
    }
  },
  "modules": [
    {
      "name": "main.Initializer",
      "config": {}
    },
    {
      "name": "loader.SuncgLoader",
      "config": {
        "path": "/volume/reconstruction_data/suncg/improved_data/version_1.0.0/house/9727d1b4bfbdd74bf73cba29f2daa429/house.json"
      }
    },
    {
      "name": "camera.SuncgCameraSampler",
      "config": {
      }
    },
    {
      "name": "materials.SuncgMaterials",
      "config": {}
    },
    {
      "name": "renderer.RgbRendererPrepare",
      "config": {
      }
    }
  ]
}