# Args: <obj_file> <output_dir>
{
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "blender_version": "blender-2.80-linux-glibc217-x86_64",
    "pip": [
      "h5py",
      "imageio"
    ]
  },
  "global": {
    "all": {
      "output_dir": "<args:1>",
      "pixel_aspect_x": 1.333333333
    }
  },
  "modules": [
    {
      "name": "main.Initializer",
      "config": {}
    },
    {
      "name": "loader.SuncgLoader",
      "config": {
        "path": "<args:0>"
      }
    },
    {
      "name": "camera.SuncgCameraSampler",
      "config": {
        "proximity_checks": {
          "min": 1.0,
          "avg": {
            "min": 1.0,
            "max": 4.0
          }
        },
        "min_interest_score": 0.4,
        "special_objects": [
          "bed",
          "chair",
          "desk",
          "kitchen_appliance",
          "table",
          "tv_stand"
        ],
        "special_objects_weight": "2"
      }
    },
    {
      "name": "materials.SuncgMaterials",
      "config": {}
    },
    {
      "name": "renderer.RgbRenderer",
      "config": {
        "output_key": "colors"
      }
    },
    {
      "name": "writer.Hdf5Writer",
      "config": {
      }
    }
  ]
}