# Args: <cam_file> <obj_file> <output_dir>
{
  "version": 1,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "blender_version": "blender-2.81-linux-glibc217-x86_64",
    "pip": [
      "h5py",
      "imageio"
    ]
  },
  "global": {
    "all": {
      "output_dir": "examples/debugging/output"
    }
  },
  "modules": [
    {
      "name": "main.Initializer",
      "config": {}
    },
    {
      "name": "loader.ObjectLoader",
      "config": {
        "path": "examples/debugging/scene.obj",
        "physics": False
      }
    },
    {
      "name": "lighting.LightLoader",
      "config": {
        "lights": [
          {
            "type": "POINT",
            "location": [5, -5, 5],
            "energy": 1000 
          }
        ]
      }
    },
    {
      "name": "object.ObjectManipulator",
      "config": {
        "instances": [
        {
          "selector": {
            "name": "getter.Object",
            "conditions": {
              "name": "Cylinder.001"
            }
          },
          "physics": True
        }
        ]
      }
    },
    {
      "name": "object.ObjectManipulator",
      "config": {
        "instances": [
        {
          "selector": {
            "name": "getter.Object",
            "conditions": {
              "name": "Cylinder*",
              "physics": True
            }
          },
          "location": {
            "name":"sampler.Uniform3d",
            "max":[1, 2, 3],
            "min":[0, 1, 2]
          },
          "rotation_euler": [1, 1, 0],
        }
        ]
      }
    },
    {
      "name": "camera.CameraLoader",
      "config": {
        "path": "examples/debugging/camera_positions",
        "file_format": "location rotation/value",
        "default_cam_param": {
          "fov": 1
        }
      }
    }
  ]
}
