name: BlenderProcHelper

on: [push, workflow_dispatch]
  
jobs:
  build-linux:
    runs-on: [self-hosted]
    strategy:
      max-parallel: 1
    steps:
    - uses: actions/checkout@v2
    - name: Run BlenderProcHelper
      run: python /home/$USER/workspace/BlenderProcHelper/github_action.py
